language: node_js
node_js:
  - "6"
  - "7"
addons:
  rethinkdb: '2.3'
before_script:
  - rethinkdb --port-offset 1 --directory rethinkdb_data2 --join localhost:29015 &
  - sleep 20
script:
  - npm test && npm run coverage
